<!doctype html><html lang=en><!-- Online page at https://ziglang.org/documentation/0.10.0/std/#root;os.unexpected_error_tracing --><head> <meta charset=utf-8> <meta name=viewport content="width=device-width,initial-scale=1"> <title>unexpected_error_tracing</title> <link href=../../style.css rel=stylesheet></head> <body class=canvas> <div class=banner> This is a beta autodoc build; expect bugs and missing information.</div> <div class=flex-main> <div id=docs class=flex-right> <div class=wrap> <section class=docs> <div style=position:relative> </div> <div id=sectNav class=""><ul id=listNav><li><a href=../../std.html class="">std</a></li><li><a href=../../std/os.html class="">os</a></li><li><a href=unexpected_error_tracing.html class=active>unexpected_error_tracing</a></li></ul></div> <div id=fnProto class=""> <div class=mobile-scroll-container><pre id=fnProtoCode class=scroll-item><span class=tok-kw>const</span> unexpected_error_tracing: bool_br_and = bool_br_and;</pre></div> </div> <div id=tldDocs class=""><p> Whether or not error.Unexpected will print its value and a stack trace. if this happens the fix is to add the error code to the corresponding switch expression, possibly introduce a new error in the error set, and send a patch to Zig. </p> </div> </section> </div> <div class=flex-filler></div> </div> </div> </body></html>